Traceback (most recent call last):
  File "/Users/sueholder/.local/share/virtualenvs/MS3-project-5hPvxxwo/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/sueholder/.local/share/virtualenvs/MS3-project-5hPvxxwo/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/sueholder/.local/share/virtualenvs/MS3-project-5hPvxxwo/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/sueholder/.local/share/virtualenvs/MS3-project-5hPvxxwo/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/sueholder/.local/share/virtualenvs/MS3-project-5hPvxxwo/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/sueholder/.local/share/virtualenvs/MS3-project-5hPvxxwo/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/sueholder/.local/share/virtualenvs/MS3-project-5hPvxxwo/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/sueholder/.local/share/virtualenvs/MS3-project-5hPvxxwo/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/sueholder/.local/share/virtualenvs/MS3-project-5hPvxxwo/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/sueholder/.local/share/virtualenvs/MS3-project-5hPvxxwo/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/sueholder/Desktop/CodeInstitute/Data-Centric/MS3-project/app/routes.py", line 304, in add_comment
    'text': request.form.get('comment')
  File "/Users/sueholder/.local/share/virtualenvs/MS3-project-5hPvxxwo/lib/python3.7/site-packages/pymongo/collection.py", line 698, in insert_one
    session=session),
  File "/Users/sueholder/.local/share/virtualenvs/MS3-project-5hPvxxwo/lib/python3.7/site-packages/pymongo/collection.py", line 612, in _insert
    bypass_doc_val, session)
  File "/Users/sueholder/.local/share/virtualenvs/MS3-project-5hPvxxwo/lib/python3.7/site-packages/pymongo/collection.py", line 600, in _insert_one
    acknowledged, _insert_command, session)
  File "/Users/sueholder/.local/share/virtualenvs/MS3-project-5hPvxxwo/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1491, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "/Users/sueholder/.local/share/virtualenvs/MS3-project-5hPvxxwo/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1384, in _retry_with_session
    return func(session, sock_info, retryable)
  File "/Users/sueholder/.local/share/virtualenvs/MS3-project-5hPvxxwo/lib/python3.7/site-packages/pymongo/collection.py", line 595, in _insert_command
    retryable_write=retryable_write)
  File "/Users/sueholder/.local/share/virtualenvs/MS3-project-5hPvxxwo/lib/python3.7/site-packages/pymongo/pool.py", line 618, in command
    self._raise_connection_failure(error)
  File "/Users/sueholder/.local/share/virtualenvs/MS3-project-5hPvxxwo/lib/python3.7/site-packages/pymongo/pool.py", line 613, in command
    user_fields=user_fields)
  File "/Users/sueholder/.local/share/virtualenvs/MS3-project-5hPvxxwo/lib/python3.7/site-packages/pymongo/network.py", line 129, in command
    codec_options, ctx=compression_ctx)
  File "/Users/sueholder/.local/share/virtualenvs/MS3-project-5hPvxxwo/lib/python3.7/site-packages/pymongo/message.py", line 707, in _op_msg
    flags, command, identifier, docs, check_keys, opts)
bson.errors.InvalidDocument: cannot encode object: Collection(Database(MongoClient(host=['cluster0-shard-00-00-qm7oy.mongodb.net:27017', 'cluster0-shard-00-01-qm7oy.mongodb.net:27017', 'cluster0-shard-00-02-qm7oy.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=False, retrywrites=True, w='majority', authsource='admin', replicaset='Cluster0-shard-0', ssl=True), 'codeflow'), 'articles._id'), of type: <class 'flask_pymongo.wrappers.Collection'>
